name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (root)
        run: npm install || echo "No root package.json"

      - name: Install dependencies (auth-service)
        run: |
          cd auth-service
          npm install

      - name: Install dependencies (booking-service)
        run: |
          cd booking-service
          npm install

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install

      - name: Run lint (auth-service)
        run: cd auth-service && npm run lint || echo "No lint"

      - name: Run lint (booking-service)
        run: cd booking-service && npm run lint || echo "No lint"

      - name: Run lint (frontend)
        run: cd frontend && npm run lint || echo "No lint"

      - name: Run tests (auth-service)
        run: cd auth-service && npm test || echo "No tests"

      - name: Run tests (booking-service)
        run: cd booking-service && npm test || echo "No tests"

      - name: Run tests (frontend)
        run: cd frontend && npm test || echo "No tests"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/bookmate
            git pull origin main
            docker-compose down
            docker-compose up -d --build
